import * as vscode from 'vscode';

export interface QuizQuestion {
    id: string;
    question: string;
    options: string[];
    correctIndex: number;
    explanation: string;
    codeSnippet: string;
}

export class ComprehensionValidator {
    private lastChangeTime: number = 0;

    /**
     * Heuristic to detect if a code block was likely pasted (AI-generated or copied).
     */
    public detectAIGeneration(event: vscode.TextDocumentChangeEvent): boolean {
        const now = Date.now();
        const duration = now - this.lastChangeTime;
        this.lastChangeTime = now;

        for (const change of event.contentChanges) {
            const addedLines = change.text.split('\n').length;
            // If more than 20 lines added in a single event, it's a "bulk" addition
            if (addedLines > 20) {
                return true;
            }
        }
        return false;
    }

    public generateQuiz(code: string): QuizQuestion {
        // Mock quiz generation based on code patterns
        // In a real app, this would be generated by an LLM analyzing the code
        return {
            id: Date.now().toString(),
            question: "This code implements a new service. How does it handle database connection exhaustion?",
            options: [
                "It uses a singleton connection pool with a max limit.",
                "It opens a new connection for every request.",
                "It relies on the database's internal queue.",
                "It doesn't handle connection limits explicitly."
            ],
            correctIndex: 0,
            explanation: "Singleton connection pools are the architectural standard for preventing port exhaustion and managing database pressure in high-concurrency environments.",
            codeSnippet: code.substring(0, 500) + "..."
        };
    }
}
